  networks:
    data_source: network
    enabled:
      - sepolia
    details:
      sepolia:
        rpc: 'wss://sepolia-1.powerpool.finance'
        agents:
          '0xf4583fc017D82c3462944A5d7E7aD380e5bfAD74':
            executor: pga
            keeper_worker_address: '0x0000000000000000000000000000000000000000'
            key_pass: myPass
            accrue_reward: false
