  networks:
    data_source: network
    enabled:
      - sepolia
    details:
      sepolia:
        rpc: 'wss://sepolia-1.powerpool.finance'
        agents:
          '0xc6420892469D344d207c701B64e578Df39Bf0918':
            executor: pga
            keeper_worker_address: '0x0000000000000000000000000000000000000000'
            key_pass: myPass
            accrue_reward: false
